using System.Text.Json.Serialization;

namespace Turkish.HRSolutions.SalaryCalculator.Tests.Parity;

/// <summary>
/// Represents a test fixture loaded from a JSON file generated by the Angular parity generator.
/// </summary>
public sealed record TestFixture
{
    [JsonPropertyName("testId")]
    public required string TestId { get; init; }

    [JsonPropertyName("description")]
    public required string Description { get; init; }

    [JsonPropertyName("input")]
    public required TestInput Input { get; init; }

    [JsonPropertyName("expectedOutput")]
    public required TestOutput ExpectedOutput { get; init; }

    [JsonPropertyName("generatedAt")]
    public required string GeneratedAt { get; init; }

    [JsonPropertyName("angularVersion")]
    public required string AngularVersion { get; init; }
}

public sealed record TestInput
{
    [JsonPropertyName("year")]
    public required int Year { get; init; }

    [JsonPropertyName("calculationMode")]
    public required string CalculationMode { get; init; }

    [JsonPropertyName("employeeTypeId")]
    public required int EmployeeTypeId { get; init; }

    [JsonPropertyName("salaryAmount")]
    public required decimal SalaryAmount { get; init; }

    [JsonPropertyName("workedDays")]
    public required decimal WorkedDays { get; init; }

    [JsonPropertyName("researchAndDevelopmentWorkedDays")]
    public required decimal ResearchAndDevelopmentWorkedDays { get; init; }

    [JsonPropertyName("disabilityDegree")]
    public required int DisabilityDegree { get; init; }

    [JsonPropertyName("agiRate")]
    public required decimal AgiRate { get; init; }

    [JsonPropertyName("educationExemptionRate")]
    public required decimal EducationExemptionRate { get; init; }

    [JsonPropertyName("isPensioner")]
    public required bool IsPensioner { get; init; }

    [JsonPropertyName("applyEmployerDiscount5746")]
    public required bool ApplyEmployerDiscount5746 { get; init; }

    [JsonPropertyName("isAgiIncludedNet")]
    public required bool IsAgiIncludedNet { get; init; }

    [JsonPropertyName("isAgiIncludedTax")]
    public required bool IsAgiIncludedTax { get; init; }

    [JsonPropertyName("applyMinWageTaxExemption")]
    public required bool ApplyMinWageTaxExemption { get; init; }

    [JsonPropertyName("isAgiCalculationEnabled")]
    public required bool IsAgiCalculationEnabled { get; init; }
}

public sealed record TestOutput
{
    [JsonPropertyName("months")]
    public required IReadOnlyList<MonthOutput> Months { get; init; }

    [JsonPropertyName("totals")]
    public required TotalsOutput Totals { get; init; }
}

public sealed record MonthOutput
{
    [JsonPropertyName("monthNumber")]
    public required int MonthNumber { get; init; }

    [JsonPropertyName("calculatedGrossSalary")]
    public required decimal CalculatedGrossSalary { get; init; }

    [JsonPropertyName("sgkBase")]
    public required decimal SgkBase { get; init; }

    [JsonPropertyName("incomeTaxBase")]
    public required decimal IncomeTaxBase { get; init; }

    [JsonPropertyName("cumulativeIncomeTaxBase")]
    public required decimal CumulativeIncomeTaxBase { get; init; }

    [JsonPropertyName("employeeSgkDeduction")]
    public required decimal EmployeeSgkDeduction { get; init; }

    [JsonPropertyName("employeeSgkExemption")]
    public required decimal EmployeeSgkExemption { get; init; }

    [JsonPropertyName("employeeFinalSgkDeduction")]
    public required decimal EmployeeFinalSgkDeduction { get; init; }

    [JsonPropertyName("employeeUnemploymentInsuranceDeduction")]
    public required decimal EmployeeUnemploymentInsuranceDeduction { get; init; }

    [JsonPropertyName("employeeUnemploymentInsuranceExemption")]
    public required decimal EmployeeUnemploymentInsuranceExemption { get; init; }

    [JsonPropertyName("employeeFinalUnemploymentInsuranceDeduction")]
    public required decimal EmployeeFinalUnemploymentInsuranceDeduction { get; init; }

    [JsonPropertyName("employeeIncomeTax")]
    public required decimal EmployeeIncomeTax { get; init; }

    [JsonPropertyName("employeeIncomeTaxExemption")]
    public required decimal EmployeeIncomeTaxExemption { get; init; }

    [JsonPropertyName("stampTax")]
    public required decimal StampTax { get; init; }

    [JsonPropertyName("employeeStampTaxExemption")]
    public required decimal EmployeeStampTaxExemption { get; init; }

    [JsonPropertyName("employerStampTaxExemption")]
    public required decimal EmployerStampTaxExemption { get; init; }

    [JsonPropertyName("totalStampTaxExemption")]
    public required decimal TotalStampTaxExemption { get; init; }

    [JsonPropertyName("employerStampTax")]
    public required decimal EmployerStampTax { get; init; }

    [JsonPropertyName("netSalary")]
    public required decimal NetSalary { get; init; }

    [JsonPropertyName("agiAmount")]
    public required decimal AgiAmount { get; init; }

    [JsonPropertyName("finalNetSalary")]
    public required decimal FinalNetSalary { get; init; }

    [JsonPropertyName("employerSgkDeduction")]
    public required decimal EmployerSgkDeduction { get; init; }

    [JsonPropertyName("employerSgkExemption")]
    public required decimal EmployerSgkExemption { get; init; }

    [JsonPropertyName("employerFinalSgkDeduction")]
    public required decimal EmployerFinalSgkDeduction { get; init; }

    [JsonPropertyName("employerUnemploymentInsuranceDeduction")]
    public required decimal EmployerUnemploymentInsuranceDeduction { get; init; }

    [JsonPropertyName("employerUnemploymentInsuranceExemption")]
    public required decimal EmployerUnemploymentInsuranceExemption { get; init; }

    [JsonPropertyName("employerFinalUnemploymentInsuranceDeduction")]
    public required decimal EmployerFinalUnemploymentInsuranceDeduction { get; init; }

    [JsonPropertyName("employerIncomeTaxExemption")]
    public required decimal EmployerIncomeTaxExemption { get; init; }

    [JsonPropertyName("employerFinalIncomeTax")]
    public required decimal EmployerFinalIncomeTax { get; init; }

    [JsonPropertyName("employerTotalSgkCost")]
    public required decimal EmployerTotalSgkCost { get; init; }

    [JsonPropertyName("employerTotalCost")]
    public required decimal EmployerTotalCost { get; init; }

    [JsonPropertyName("totalSgkExemption")]
    public required decimal TotalSgkExemption { get; init; }

    [JsonPropertyName("employeeMinWageTaxExemption")]
    public required decimal EmployeeMinWageTaxExemption { get; init; }
}

public sealed record TotalsOutput
{
    [JsonPropertyName("calculatedGrossSalary")]
    public required decimal CalculatedGrossSalary { get; init; }

    [JsonPropertyName("netSalary")]
    public required decimal NetSalary { get; init; }

    [JsonPropertyName("finalNetSalary")]
    public required decimal FinalNetSalary { get; init; }

    [JsonPropertyName("employerTotalCost")]
    public required decimal EmployerTotalCost { get; init; }

    [JsonPropertyName("totalSgkExemption")]
    public required decimal TotalSgkExemption { get; init; }
}

/// <summary>
/// Result of comparing a single field between expected and actual values.
/// </summary>
public sealed record FieldComparisonResult(
    string FieldName,
    decimal Expected,
    decimal Actual,
    decimal Difference,
    bool Passed
);

/// <summary>
/// Result of comparing a complete test fixture.
/// </summary>
public sealed record TestComparisonResult
{
    public required string TestId { get; init; }
    public required string Description { get; init; }
    public required bool Passed { get; init; }
    public required IReadOnlyList<FieldComparisonResult> FieldResults { get; init; }
    public string? ErrorMessage { get; init; }

    public IEnumerable<FieldComparisonResult> FailedFields =>
        FieldResults.Where(f => !f.Passed);
}