<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(CurrentNetVersion)</TargetFramework>
    <NoWarn>
      $(NoWarn);CA1707
    </NoWarn>
    <NoError>
      $(NoError);CA1707
    </NoError>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CliWrap"/>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection"/>
    <PackageReference Include="TUnit"/>
    <PackageReference Include="TestableIO.System.IO.Abstractions.TestingHelpers"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Turkish.HRSolutions.SalaryCalculator\Turkish.HRSolutions.SalaryCalculator.csproj"/>
  </ItemGroup>

</Project>
